### ISSUE TITLE
PDF table extraction tools

### ISSUE THREAD

**Issue by Rainiefantasy** [aim-rsf/cprd-data-wrangle#18]
**Question/topic for discussion:**
Can the manual table creation (pdf -> csv) be simplified? This could be great as this would mean the code would be generalisable. For example, this may help in addressing creating potential workflows for CPRD Gold not just Aurum #12 .

**Tasks:**
- [ ] To look into PDF table extraction tools which can assist this process
- [ ] Are these tools flexible and how accurate are they? If they are prone to error maybe better to leave as is
- [ ] If it works, maybe consider testing on Gold?

**Comment by RayStick** [comment]
**Some context for this task**
1. CPRD's data specifications ([example](https://www.cprd.com/sites/default/files/2022-02/CPRD%20Aurum%20Data%20Specification%20v2.7%20%28002%29.pdf)) contain all the info we want for this pipeline but they are in PDF - if it's easy to extract the metadata tables into machine readable format that's great, but don't do it if it's a messy big task. We can think about requesting them in a different format
2. HDRUK allow you to download a structural metadata csv for CPRD Aurum (https://healthdatagateway.org/en/dataset/692) however the file only contains 'column name' not 'field name' and we do not know if it is kept up to date

**Comment by RayStick** [comment]
Make a new issue to contextualize the limitation of using the PDF - tag it with 'help wanted' from CPRD or HDRUK
